//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/10/2014 14:40:05
namespace Aphrodite.Data.Models
{
    /// <summary>
    /// There are no comments for UserSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("UserSingle")]
    public partial class UserSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<User>
    {
        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for Matches in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Aphrodite.Data.Models.Match> Matches
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Matches == null))
                {
                    this._Matches = Context.CreateQuery<global::Aphrodite.Data.Models.Match>(GetPath("Matches"));
                }
                return this._Matches;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Aphrodite.Data.Models.Match> _Matches;
        /// <summary>
        /// There are no comments for Photos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Aphrodite.Data.Models.Photo> Photos
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Photos == null))
                {
                    this._Photos = Context.CreateQuery<global::Aphrodite.Data.Models.Photo>(GetPath("Photos"));
                }
                return this._Photos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Aphrodite.Data.Models.Photo> _Photos;
    }
    /// <summary>
    /// There are no comments for User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("User")]
    public partial class User : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="sex">Initial value of Sex.</param>
        /// <param name="sexualPreference">Initial value of SexualPreference.</param>
        /// <param name="age">Initial value of Age.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        /// <param name="lastLogin">Initial value of LastLogin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static User CreateUser(int ID, 
                    int sex, 
                    int sexualPreference, 
                    int age, 
                    global::System.DateTimeOffset createdOn, 
                    global::System.DateTimeOffset lastLogin)
        {
            User user = new User();
            user.ID = ID;
            user.Sex = sex;
            user.SexualPreference = sexualPreference;
            user.Age = age;
            user.CreatedOn = createdOn;
            user.LastLogin = lastLogin;
            return user;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ID")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Email")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Password")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserName")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Sex in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Sex")]
        public int Sex
        {
            get
            {
                return this._Sex;
            }
            set
            {
                this.OnSexChanging(value);
                this._Sex = value;
                this.OnSexChanged();
                this.OnPropertyChanged("Sex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Sex;
        partial void OnSexChanging(int value);
        partial void OnSexChanged();
        /// <summary>
        /// There are no comments for Property SexualPreference in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SexualPreference")]
        public int SexualPreference
        {
            get
            {
                return this._SexualPreference;
            }
            set
            {
                this.OnSexualPreferenceChanging(value);
                this._SexualPreference = value;
                this.OnSexualPreferenceChanged();
                this.OnPropertyChanged("SexualPreference");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _SexualPreference;
        partial void OnSexualPreferenceChanging(int value);
        partial void OnSexualPreferenceChanged();
        /// <summary>
        /// There are no comments for Property Age in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Age")]
        public int Age
        {
            get
            {
                return this._Age;
            }
            set
            {
                this.OnAgeChanging(value);
                this._Age = value;
                this.OnAgeChanged();
                this.OnPropertyChanged("Age");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Age;
        partial void OnAgeChanging(int value);
        partial void OnAgeChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedOn")]
        public global::System.DateTimeOffset CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.DateTimeOffset _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTimeOffset value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property LastLogin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastLogin")]
        public global::System.DateTimeOffset LastLogin
        {
            get
            {
                return this._LastLogin;
            }
            set
            {
                this.OnLastLoginChanging(value);
                this._LastLogin = value;
                this.OnLastLoginChanged();
                this.OnPropertyChanged("LastLogin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.DateTimeOffset _LastLogin;
        partial void OnLastLoginChanging(global::System.DateTimeOffset value);
        partial void OnLastLoginChanged();
        /// <summary>
        /// There are no comments for Property Matches in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Matches")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Aphrodite.Data.Models.Match> Matches
        {
            get
            {
                return this._Matches;
            }
            set
            {
                this.OnMatchesChanging(value);
                this._Matches = value;
                this.OnMatchesChanged();
                this.OnPropertyChanged("Matches");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Aphrodite.Data.Models.Match> _Matches = new global::Microsoft.OData.Client.DataServiceCollection<global::Aphrodite.Data.Models.Match>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnMatchesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Aphrodite.Data.Models.Match> value);
        partial void OnMatchesChanged();
        /// <summary>
        /// There are no comments for Property Photos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Photos")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Aphrodite.Data.Models.Photo> Photos
        {
            get
            {
                return this._Photos;
            }
            set
            {
                this.OnPhotosChanging(value);
                this._Photos = value;
                this.OnPhotosChanged();
                this.OnPropertyChanged("Photos");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Aphrodite.Data.Models.Photo> _Photos = new global::Microsoft.OData.Client.DataServiceCollection<global::Aphrodite.Data.Models.Photo>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnPhotosChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Aphrodite.Data.Models.Photo> value);
        partial void OnPhotosChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MatchSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MatchSingle")]
    public partial class MatchSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Match>
    {
        /// <summary>
        /// Initialize a new MatchSingle object.
        /// </summary>
        public MatchSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MatchSingle object.
        /// </summary>
        public MatchSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Aphrodite.Data.Models.UserSingle User
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._User == null))
                {
                    this._User = new global::Aphrodite.Data.Models.UserSingle(this.Context, GetPath("User"));
                }
                return this._User;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Aphrodite.Data.Models.UserSingle _User;
    }
    /// <summary>
    /// There are no comments for Match in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MatchID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("MatchID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Match")]
    public partial class Match : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Match object.
        /// </summary>
        /// <param name="matchID">Initial value of MatchID.</param>
        /// <param name="userIDFrom">Initial value of UserIDFrom.</param>
        /// <param name="userIDTo">Initial value of UserIDTo.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Match CreateMatch(int matchID, int userIDFrom, int userIDTo)
        {
            Match match = new Match();
            match.MatchID = matchID;
            match.UserIDFrom = userIDFrom;
            match.UserIDTo = userIDTo;
            return match;
        }
        /// <summary>
        /// There are no comments for Property MatchID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MatchID")]
        public int MatchID
        {
            get
            {
                return this._MatchID;
            }
            set
            {
                this.OnMatchIDChanging(value);
                this._MatchID = value;
                this.OnMatchIDChanged();
                this.OnPropertyChanged("MatchID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _MatchID;
        partial void OnMatchIDChanging(int value);
        partial void OnMatchIDChanged();
        /// <summary>
        /// There are no comments for Property Pending in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Pending")]
        public string Pending
        {
            get
            {
                return this._Pending;
            }
            set
            {
                this.OnPendingChanging(value);
                this._Pending = value;
                this.OnPendingChanged();
                this.OnPropertyChanged("Pending");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Pending;
        partial void OnPendingChanging(string value);
        partial void OnPendingChanged();
        /// <summary>
        /// There are no comments for Property Matches in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Matches")]
        public string Matches
        {
            get
            {
                return this._Matches;
            }
            set
            {
                this.OnMatchesChanging(value);
                this._Matches = value;
                this.OnMatchesChanged();
                this.OnPropertyChanged("Matches");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Matches;
        partial void OnMatchesChanging(string value);
        partial void OnMatchesChanged();
        /// <summary>
        /// There are no comments for Property UserIDFrom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserIDFrom")]
        public int UserIDFrom
        {
            get
            {
                return this._UserIDFrom;
            }
            set
            {
                this.OnUserIDFromChanging(value);
                this._UserIDFrom = value;
                this.OnUserIDFromChanged();
                this.OnPropertyChanged("UserIDFrom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _UserIDFrom;
        partial void OnUserIDFromChanging(int value);
        partial void OnUserIDFromChanged();
        /// <summary>
        /// There are no comments for Property UserIDTo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserIDTo")]
        public int UserIDTo
        {
            get
            {
                return this._UserIDTo;
            }
            set
            {
                this.OnUserIDToChanging(value);
                this._UserIDTo = value;
                this.OnUserIDToChanged();
                this.OnPropertyChanged("UserIDTo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _UserIDTo;
        partial void OnUserIDToChanging(int value);
        partial void OnUserIDToChanged();
        /// <summary>
        /// There are no comments for Property User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("User")]
        public global::Aphrodite.Data.Models.User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this.OnUserChanging(value);
                this._User = value;
                this.OnUserChanged();
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Aphrodite.Data.Models.User _User;
        partial void OnUserChanging(global::Aphrodite.Data.Models.User value);
        partial void OnUserChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PhotoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PhotoSingle")]
    public partial class PhotoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Photo>
    {
        /// <summary>
        /// Initialize a new PhotoSingle object.
        /// </summary>
        public PhotoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PhotoSingle object.
        /// </summary>
        public PhotoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Aphrodite.Data.Models.UserSingle User
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._User == null))
                {
                    this._User = new global::Aphrodite.Data.Models.UserSingle(this.Context, GetPath("User"));
                }
                return this._User;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Aphrodite.Data.Models.UserSingle _User;
    }
    /// <summary>
    /// There are no comments for Photo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PhotoID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PhotoID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Photo")]
    public partial class Photo : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Photo object.
        /// </summary>
        /// <param name="userID">Initial value of UserID.</param>
        /// <param name="photoID">Initial value of PhotoID.</param>
        /// <param name="priority">Initial value of Priority.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Photo CreatePhoto(int userID, int photoID, int priority)
        {
            Photo photo = new Photo();
            photo.UserID = userID;
            photo.PhotoID = photoID;
            photo.Priority = priority;
            return photo;
        }
        /// <summary>
        /// There are no comments for Property UserID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserID")]
        public int UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this.OnUserIDChanging(value);
                this._UserID = value;
                this.OnUserIDChanged();
                this.OnPropertyChanged("UserID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _UserID;
        partial void OnUserIDChanging(int value);
        partial void OnUserIDChanged();
        /// <summary>
        /// There are no comments for Property PhotoDir in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PhotoDir")]
        public string PhotoDir
        {
            get
            {
                return this._PhotoDir;
            }
            set
            {
                this.OnPhotoDirChanging(value);
                this._PhotoDir = value;
                this.OnPhotoDirChanged();
                this.OnPropertyChanged("PhotoDir");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _PhotoDir;
        partial void OnPhotoDirChanging(string value);
        partial void OnPhotoDirChanged();
        /// <summary>
        /// There are no comments for Property CurrentAvatar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrentAvatar")]
        public string CurrentAvatar
        {
            get
            {
                return this._CurrentAvatar;
            }
            set
            {
                this.OnCurrentAvatarChanging(value);
                this._CurrentAvatar = value;
                this.OnCurrentAvatarChanged();
                this.OnPropertyChanged("CurrentAvatar");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _CurrentAvatar;
        partial void OnCurrentAvatarChanging(string value);
        partial void OnCurrentAvatarChanged();
        /// <summary>
        /// There are no comments for Property PhotoID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PhotoID")]
        public int PhotoID
        {
            get
            {
                return this._PhotoID;
            }
            set
            {
                this.OnPhotoIDChanging(value);
                this._PhotoID = value;
                this.OnPhotoIDChanged();
                this.OnPropertyChanged("PhotoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _PhotoID;
        partial void OnPhotoIDChanging(int value);
        partial void OnPhotoIDChanged();
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Priority")]
        public int Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this._Priority = value;
                this.OnPriorityChanged();
                this.OnPropertyChanged("Priority");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Priority;
        partial void OnPriorityChanging(int value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("User")]
        public global::Aphrodite.Data.Models.User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this.OnUserChanging(value);
                this._User = value;
                this.OnUserChanged();
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Aphrodite.Data.Models.User _User;
        partial void OnUserChanging(global::Aphrodite.Data.Models.User value);
        partial void OnUserChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Aphrodite.Data.Models.User as global::Aphrodite.Data.Models.UserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Aphrodite.Data.Models.UserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aphrodite.Data.Models.User> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Aphrodite.Data.Models.UserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Aphrodite.Data.Models.Match as global::Aphrodite.Data.Models.MatchSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Aphrodite.Data.Models.MatchSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aphrodite.Data.Models.Match> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Aphrodite.Data.Models.MatchSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Aphrodite.Data.Models.Photo as global::Aphrodite.Data.Models.PhotoSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Aphrodite.Data.Models.PhotoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aphrodite.Data.Models.Photo> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Aphrodite.Data.Models.PhotoSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Aphrodite.Data.Models", "Aphrodite.Data.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Aphrodite.Data.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Aphrodite.Data.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Aphrodite.Data.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Aphrodite.Data.Models.User> User
        {
            get
            {
                if ((this._User == null))
                {
                    this._User = base.CreateQuery<global::Aphrodite.Data.Models.User>("User");
                }
                return this._User;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Aphrodite.Data.Models.User> _User;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToUser(global::Aphrodite.Data.Models.User user)
        {
            base.AddObject("User", user);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Aphrodite.Data.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""User"">
        <Key>
          <PropertyRef Name=""ID"" />
        </Key>
        <Property Name=""ID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""Password"" Type=""Edm.String"" />
        <Property Name=""UserName"" Type=""Edm.String"" />
        <Property Name=""Sex"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""SexualPreference"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Age"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Location"" Type=""Edm.String"" />
        <Property Name=""CreatedOn"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""LastLogin"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <NavigationProperty Name=""Matches"" Type=""Collection(Aphrodite.Data.Models.Match)"" />
        <NavigationProperty Name=""Photos"" Type=""Collection(Aphrodite.Data.Models.Photo)"" />
      </EntityType>
      <EntityType Name=""Match"">
        <Key>
          <PropertyRef Name=""MatchID"" />
        </Key>
        <Property Name=""MatchID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Pending"" Type=""Edm.String"" />
        <Property Name=""Matches"" Type=""Edm.String"" />
        <Property Name=""UserIDFrom"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""UserIDTo"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""User"" Type=""Aphrodite.Data.Models.User"" />
      </EntityType>
      <EntityType Name=""Photo"">
        <Key>
          <PropertyRef Name=""PhotoID"" />
        </Key>
        <Property Name=""UserID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PhotoDir"" Type=""Edm.String"" />
        <Property Name=""CurrentAvatar"" Type=""Edm.String"" />
        <Property Name=""PhotoID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Priority"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""User"" Type=""Aphrodite.Data.Models.User"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""User"" EntityType=""Aphrodite.Data.Models.User"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
    }
}
